json.id product.id
json.item_name product.item_name
json.item_price product.item_price
json.image_url product.image_url
json.item_description product.item_description
json.is_discounted? product.is_discounted?
json.tax_result product.tax_result
json.total_result product.total_result
json.created_at product.created_at
json.updated_at product.updated_at